name: Chunliang Yang @ TAMU-ISE
url: https://chunliangyang.github.io
description: Home page of Chunliang Yang @ TAMU-ISE. He is now a master student at Texas A&M University (TAMU-ISE)
destination: ./_site
twitter: d
lsi: false
port: 4000
markdown: kramdown
future: true
kramdown:
  parse_block_html: true
  syntax_highlighter: rouge
permalink: pretty
#seo
tagline: Home site for Chunliang Yang @ TAMU-ISE | Master Student 
#paginate: 5
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

exclude:
  - .travis.yml
  - validate.rb
  - README.md
  - Gemfile
  - Gemfile.lock
  - bower_components
  - update-vendor-deps.sh
  - vendor/bundle
  - vendor/bower.json
